OUTFILE = opentitus
OBJS = 	unsqz.o src/sqz.o opentitus.o src/audio.o src/common.o src/draw.o src/enemies.o src/engine.o src/elevators.o src/fonts.o src/gates.o src/keyboard.o src/level.o src/menu.o src/objects.o src/original.o src/player.o src/reset.o src/scroll.o src/settings.o src/sprites.o src/sqz.o src/tile_animation.o src/viewimage.o opl/libopl_kos.a
CFLAGS = -Os -I./include -I./opl -DKOLIBRI
LIBS = -lm -lSDL -s
include $(MENUETDEV)/makefiles/Makefile_for_program
